/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconCustomLogo: typeof import('~icons/custom/logo')['default']
    IconParkOutlineFullScreen: typeof import('~icons/icon-park-outline/full-screen')['default']
    IconParkOutlineMoon: typeof import('~icons/icon-park-outline/moon')['default']
    IconParkOutlineOffScreen: typeof import('~icons/icon-park-outline/off-screen')['default']
    IconParkOutlineSunOne: typeof import('~icons/icon-park-outline/sun-one')['default']
    IconParkOutlineTranslate: typeof import('~icons/icon-park-outline/translate')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
